[platformio]
src_dir = Cobra_Driver
lib_dir = libraries

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs

lib_deps =
    bblanchon/ArduinoJson @ 6.21.3
    adafruit/Adafruit SSD1306 @ 2.5.7
    adafruit/Adafruit GFX Library @ 1.11.7
    wollewald/INA219_WE @ 1.2.9
